apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: my-release-metallb-config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.0.20-192.168.0.29

