kind: Deployment
apiVersion: apps/v1
metadata:
  name: plex.k3s.example.com
  namespace: plex
  labels:
    app: plex-app
spec:
  selector:
    matchLabels:
      app: plex-app
  replicas: 1
  template:
    metadata:
      namespace: plex
      labels:
        app: plex-app
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker
          ports:
          - containerPort: 32400
          - containerPort: 32469
          - containerPort: 1900
            protocol: UDP
          - containerPort: 5353
            protocol: UDP
          - containerPort: 32410
            protocol: UDP
          - containerPort: 32412
            protocol: UDP
          - containerPort: 32413
            protocol: UDP
          - containerPort: 32414
            protocol: UDP
          envFrom:
          - configMapRef:
              name: plex-config
          # Add Persistent Volume Claim

