apiVersion: v1
kind: Service
metadata:
  name: plex-service-tcp
  namespace: plex
  annotations:
    metallb.universe.tf/allow-shared-ip: "plex"
spec:
  selector:
    app: plex-app
  ports:
    - name: pms-1
      port: 32400
      targetPort: 32400
    - name: pms-https
      port: 443
      targetPort: 32400
    - name: pms-http
      port: 80
      targetPort: 32400
    - name: dlna-2
      port: 32469
      targetPort: 32469
  type: LoadBalancer
  loadBalancerIP: 192.168.0.21
---
apiVersion: v1
kind: Service
metadata:
  name: plex-service-udp
  namespace: plex
  annotations:
    metallb.universe.tf/allow-shared-ip: "plex"
spec:
  selector:
    app: plex-app
  ports:
    - name: dlna-1
      protocol: UDP
      port: 1900
      targetPort: 1900
    - name: mdns
      protocol: UDP
      port: 5353
      targetPort: 5353
    - name: gdm-0
      protocol: UDP
      port: 32410
      targetPort: 32410
    - name: gdm-2
      protocol: UDP
      port: 32412
      targetPort: 32412
    - name: gdm-3
      protocol: UDP
      port: 32413
      targetPort: 32413
    - name: gdm-4
      protocol: UDP
      port: 32414
      targetPort: 32414
  type: LoadBalancer
  loadBalancerIP: 192.168.0.21

